export default {
  data() {
    return {
      menuData: [
        {
          id: 1,
          title: "What We Do",
          megaMenu: true,
          link: "/",
          mega_menus: [
            {
              title: "BMC",
              link: "/bmc",
              submenus: [
                { title: "BMC Helix ITSM", link: "/bmc-helix-itsm" },
                { title: "BMC Helix Remedyforce", link: "/bmc-helix-remedyforce" },
                { title: "BMC Helix Discovery", link: "/bmc-helix-discovery" },
                { title: "BMC Truesight", link: "/bmc-truesight" },
                { title: "BMC Control-M", link: "/bmc-control-m" },
                { title: "BMC Smart Reporting", link: "/bmc-smart-reporting" },
                { title: "BMC Client Management", link: "/bmc-client-management" },
                { title: "BMC Helix DWP", link: "/bmc-helix-dwp" },
                { title: "BMC Blade Logic", link: "/coming-soon" },
                { title: "BMC Training", link: "/coming-soon" },
              ],
            },
            {
              title: "Salesforce",
              link: "/salesforce",
              submenus: [
                { title: "Salesforce Sales Cloud", link: "/coming-soon" },
                { title: "Salesforce Service Cloud", link: "/coming-soon" },
                { title: "Salesforce Commerce Cloud", link: "/coming-soon" },
                { title: "Salesforce Marketing Cloud", link: "/coming-soon" },
                { title: "Salesforce Comunity Cloud", link: "/coming-soon" },
                { title: "Salesforce Integration Cloud", link: "/coming-soon" },
                { title: "Salesforce Data Cloud", link: "/coming-soon" },
              ],
            },
            {
              title: "ServiceNow",
              link: "/snow",
              submenus: [
                { title: "ServiceNow It Service Management", link: "/coming-soon" },
                { title: "ServiceNow IT Workflows", link: "/coming-soon" },
                { title: "ServiceNow Knowledge Management", link: "/coming-soon" },
                { title: "ServiceNow Audit Management", link: "/coming-soon" },
                { title: "ServiceNow Configuration Compliance", link: "/coming-soon" },
                { title: "ServiceNow IT Operations Management", link: "/coming-soon" },
              ],
            },
            {
              title: "AWS",
              link: "/aws",
              submenus: [
                { title: "Aws Consulting", link: "/coming-soon" },
                { title: "Aws Cloud Migration", link: "/coming-soon" },
                { title: "Aws Cloud Security", link: "/coming-soon" },
                { title: "Managed Cloud Services", link: "/coming-soon" },
                { title: "Serverless Computing", link: "/coming-soon" },
                { title: "Aws Market Enablement", link: "/coming-soon" },
              ],
            },
            {
              title: "SAP",
              link: "/sap",
              submenus: [
                { title: "Sap Hana", link: "/coming-soon" },
                { title: "Sap Crm", link: "/coming-soon" },
                { title: "Sap Erp", link: "/coming-soon" },
                { title: "Sap Hr", link: "/coming-soon" },
                { title: "Sap Business Objects", link: "/coming-soon" },
                { title: "Sap Plm", link: "/coming-soon" },
              ],
            },
            {
              title: "Analytics",
              link: "/coming-soon",
              submenus: [
                { title: "Qlikview", link: "/coming-soon" },
                { title: "Tableau", link: "/coming-soon" },
                { title: "Power-Bi", link: "/coming-soon" },
                { title: "QlikSense", link: "/coming-soon" },
                { title: "Sap-Analytics", link: "/coming-soon" },
              ],
            },
            {
              title: "Microsoft Dynamics 365",
              link: "/microsoft dynamics 365",
              submenus: [
                { title: "Business Central", link: "/coming-soon" },
                { title: "Finance", link: "/coming-soon" },
                { title: "Supply Chain Management", link: "/coming-soon" },
                { title: "Sales", link: "/coming-soon" },
                { title: "Customer Service", link: "/coming-soon" },
                { title: "Project Operations", link: "/coming-soon" },
                { title: "Marketing", link: "/coming-soon" },
                { title: "Human Resource", link: "/coming-soon" },

              ],
            },
            {
              title: "Oracle",
              link: "/oracle",
              submenus: [
                { title: "OCI AI Services", link: "/coming-soon" },
                { title: "Application Development", link: "/coming-soon" },
                { title: "OCI Solutions", link: "/oci-solutions" },
                { title: "Oracle Managed services", link: "/coming-soon" },
                { title: "Advisory Services", link: "/coming-soon" },
              ],
            },
          ],
        },
        {
          id: 2,
          title: "Offering",
          megaMenu: true,
          link: "/",
          mega_menus: [
            {
              title: "Solution",
              link: "/coming-soon",
              submenus: [
                { title: "ERP", link: "/coming-soon" },
                { title: "Operations Management", link: "/coming-soon" },
                { title: "Finanacial Management", link: "/coming-soon" },
                { title: "Payment Management", link: "/coming-soon" },
                { title: "Supply Chain Management", link:"/coming-soon" },
                { title: "Data Analytics", link: "/coming-soon" },
                { title: "Asset Management", link: "/coming-soon" },
                { title: "Fleet Management", link: "/coming-soon" },
                { title: "Human Resources", link: "/coming-soon" },
                { title: "eLearning", link: "/coming-soon" },
                { title: "Document Management", link: "/coming-soon" },
                { title: "Project Management", link: "/coming-soon" },
                { title: "Ecommerce", link:"/coming-soon" },
                { title: "Marketing & Advertising", link: "/coming-soon" },
                { title: "Content Management", link: "/coming-soon" },
                { title: "Kiosk Software", link:"/coming-soon" },
                { title: "Web Portals", link:"/coming-soon" },
              ],
            },
            {
              title: "Services",
              link: "/coming-soon",
              submenus: [
                { title: "Software Development", link: "/coming-soon" },
                { title: "Web Development", link: "/coming-soon" },
                { title: "Mobile App Development", link: "/coming-soon" },
                { title: "Testing & QA", link: "/coming-soon" },
                { title: "Application Services", link: "/coming-soon" },
                { title: "UI/UX Design", link: "/coming-soon" },
                { title: "Infrastructure Services", link: "/coming-soon" },
                { title: "Digital Transformation", link: "/coming-soon" },
                { title: "Managed IT Services", link:"/coming-soon" },
                { title: "IT Outsourcing", link: "/coming-soon"},
                { title: "IT Consulting", link: "/coming-soon" },
                { title: "IT Support", link: "/coming-soon" },
                { title: "Data Analytics", link: "/coming-soon" },
                { title: "Cybersecurity", link: "/coming-soon" },

              ],
            },
          ],
        },
        // {
        //   id: 3,
        //   hasDropdown: true,
        //   title: "Innovation",
        //   link: "/",
        //   submenus: [
        //     { title: "Cloud", link: "/cloud" },
        //     { title: "Software as a Service(SAAS)", link: "/software-as-a-service" },
        //     { title: "Internet of Things", link: "/internet-of-things" },
        //     { title: "Big Data", link: "/big-data" },
        //     { title: "Data Science", link: "/data-science" },
        //     { title: "Machine Learning", link: "/machine-learning" },
        //     { title: "Artificial Intelligence", link: "/artificial-intelligence" },
        //     { title: "Blockchain", link: "/blockchain" },
        //     { title: "Virtual Reality", link: "/virtual-reality" },
        //     { title: "Computer Vision", link: "/computer-vision" },
        //     { title: "Microsoft", link: "/microsoft" },
        //     { title: "Azure", link: "/azure" },
        //     { title: "Power Apps", link: "/power-apps" },
        //     { title: "Dynamics 365", link: "/dynamics-three-sixty-five" },
        //     { title: "Sharepoint and Office 365", link: "/sharepoint-and-office-three-sixty-five" },
        //     { title: "PowerBI", link: "/powerbi" },
        //     { title: "Aamzon Web Services", link: "/aamzon-web-services" },
        //     { title: "Adobe Commerce", link: "/adobe-commerce" },
        //     { title: "Pimcore", link: "/pimcore" },
        //     { title: "Metaverse as a Service (MAAS)", link: "/metaverse-as-a-service" },
        //     { title: "IAAS", link: "/iaas" },

        //   ],
        // },

        {
          id: 3,
          title: "Innovation",
          megaMenu: true,
          link: "/",
          mega_menus: [
            {
              title: "Technology",
              link: "/",
              submenus: [
                { title: "Cloud", link: "/coming-soon" },
            { title: "Software as a Service(SAAS)", link: "/coming-soon"},
            { title: "Internet of Things", link: "/coming-soon" },
            { title: "Big Data", link: "/coming-soon" },
            { title: "Data Science", link: "/coming-soon" },
            { title: "Machine Learning", link: "/coming-soon" },
            { title: "Artificial Intelligence", link: "/coming-soon" },
            { title: "Blockchain", link: "/coming-soon"},
            { title: "Virtual Reality", link: "/coming-soon" },
            { title: "Computer Vision", link: "/coming-soon" },
            { title: "Microsoft", link: "/coming-soon" },
            { title: "Azure", link:"/coming-soon" },
            { title: "Power Apps", link: "/coming-soon" },
            { title: "Dynamics 365", link: "/coming-soon" },
            { title: "Sharepoint and Office 365", link: "/coming-soon" },
            { title: "PowerBI", link: "/coming-soon" },
            { title: "Aamzon Web Services", link: "/coming-soon"},
            { title: "Adobe Commerce", link: "/coming-soon"},
            { title: "Pimcore", link: "/coming-soon" },
            { title: "Metaverse as a Service (MAAS)", link:"/coming-soon"},
            { title: "IAAS", link: "/coming-soon" },

              ],
            },
            {
              title: "Industries",
              link: "/",
              submenus: [
                { title: "Financial Services", link: "/coming-soon" },
                { title: "Banking", link: "/coming-soon" },
                { title: "Insurance", link: "/coming-soon" },
                { title: "Lendin", link: "/coming-soon" },
                { title: "Investment", link: "/coming-soon" },
                { title: "Fintech", link: "/coming-soon" },
                { title: "Payments", link: "/coming-soon" },
                { title: "Retail", link: "/coming-soon"},
                { title: "Healthcare", link: "/coming-soon" },
                { title: "Manufacturing", link: "/coming-soon" },
                { title: "Professional Services", link: "/coming-soon" },
                { title: "Transportation and Logistics", link: "/coming-soon" },
                { title: "Telecommunications", link: "/coming-soon" },
                { title: "Oil and Gas", link: "/coming-soon" },
                { title: "Construction", link: "/coming-soon"},
                { title: "Travel and Hospitality", link: "/coming-soon" },


              ],
            },
          ],
        },
        {
          id: 4,
          hasDropdown: true,
          title: "Staff Augmentation",
          link: "/",
          submenus: [
            { title: "Java", link: "/coming-soon" },
            { title: ".NET", link: "/coming-soon" },
            { title: "Python", link: "/coming-soon"},
            { title: "PHP", link: "/coming-soon" },
            { title: "Golang", link:"/coming-soon" },
            { title: "C++", link: "/coming-soon" },
            { title: "Node.js", link: "/coming-soon" },
            { title: "React Native", link: "/coming-soon" },
            { title: "JavaScript", link: "/coming-soon"},
            { title: "Mobile", link: "/coming-soon" },

          ],
        },
        {
          id: 5,
          hasDropdown: true,
          title: "Company",
          link: "/",
          submenus: [
            { title: "About Us", link: "/about" },
            { title: "Blogs", link: "/blogs" },
            { title: "Case Studies", link: "/case-studies" },
            { title: "Success Story", link: "/success-story" },
            { title: "eBook", link: "/ebook" },
            { title: "Glossary", link: "/glossary" },
            { title: "Job Opening", link: "/job-opening" },
            { title: "Testimonials", link: "/testimonials" },
            { title: "Company Brouchure", link: "/coming-soon" },
            { title: "Free Trail", link: "/freetrail" },
            { title: "Contact Us", link: "/contact" },
          ],
        },
        // {
        //   id: 5,
        //   title: "Company",
        //   megaMenu: true,
        //   link: "/",
        //   pages: true,
        //   mega_menus: [
        //     {
        //       title: "Page Layout 1",
        //       link: "#",
        //       submenus: [
        //         { title: "About Us", link: "/about" },
        //         { title: "About Me", link: "/about-me" },
        //         { title: "Service Creative", link: "/services" },
        //         { title: "Service Standard", link: "/services-2" },
        //         { title: "Service Basic", link: "/services-3" },
        //         { title: "Service Details", link: "/service-details" },
        //         { title: "Help Center", link: "/help" },
        //       ],
        //     },
        //     {
        //       title: "Page Layout 2",
        //       link: "#",
        //       submenus: [
        //         { title: "Team Classic", link: "/team" },
        //         { title: "Team Details", link: "/team-details" },
        //         { title: "Event Details", link: "/event-details" },
        //         { title: "Job List", link: "/job" },
        //         { title: "Job Details", link: "/job-details" },
        //         { title: "Pricing Table", link: "/pricing" },
        //         { title: "Coming soon", link: "/coming-soon" },
        //       ],
        //     },
        //     {
        //       title: "Page Layout 3",
        //       link: "#",
        //       submenus: [
        //         { title: "Shop", link: "/shop" },
        //         { title: "Shop Right Sidebar", link: "/shop-right-sidebar" },
        //         { title: "Shop Details", link: "/product-details" },
        //         { title: "FAQs", link: "/faq" },
        //         { title: "Search Result", link: "/search" },
        //         { title: "Privacy & Policy", link: "/policy" },
        //         { title: "Terms & Conditions", link: "/terms" },
        //       ],
        //     },
        //     {
        //       title: "Page Layout 4",
        //       link: "#",
        //       submenus: [
        //         { title: "Error 404", link: "/404" },
        //         { title: "Login", link: "/login" },
        //         { title: "Register", link: "/register" },
        //         { title: "Forgot Password", link: "/forgot" },
        //         { title: "My Cart", link: "/cart" },
        //         { title: "My Wishlist", link: "/wishlist" },
        //         { title: "Checkout", link: "/checkout" },
        //       ],
        //     },
        //   ],
        // },
        // {
        //   id: 6,
        //   hasDropdown: true,
        //   title: "Contact",
        //   link: "/contact",
        //   submenus: [
        //     { title: "Contact Agency", link: "/contact" },
        //     { title: "Contact: Classic", link: "/contact-2" },
        //   ],
        // },
      ],
    };
  },
};
