export default {
  data() {
    return {
      menuData: [
        {
          id: 1,
          title: "What We Do",
          megaMenu: true,
          link: "/",
          mega_menus: [
            {
              title: "BMC",
              link: "#",
              submenus: [
                { title: "BMC Helix ITSM", link: "/bmc-helix-itsm" },
                { title: "BMC Helix Remedyforce", link: "/bmc-helix-remedyforce" },
                { title: "BMC Helix Discovery", link: "/bmc-helix-discovery" },
                { title: "BMC Truesight", link: "/bmc-truesight" },
                { title: "BMC Control-M", link: "/bmc-control-m" },
                { title: "BMC Smart Reporting", link: "/bmc-smart-reporting" },
                { title: "BMC Client Management", link: "/bmc-client-management" },
                { title: "BMC Helix DWP", link: "/bmc-helix-dwp" },
                { title: "BMC Blade Logic", link: "/bmc-blade-logic" },
                { title: "BMC Training", link: "/bmc-training" },
              ],
            },
            {
              title: "Salesforce",
              link: "#",
              submenus: [
                { title: "Salesforce Sales Cloud", link: "/salesforce-sales-cloud" },
                { title: "Salesforce Service Cloud", link: "/salesforce-service-cloud" },
                { title: "Salesforce Commerce Cloud", link: "/salesforce-commerce-cloud" },
                { title: "Salesforce Marketing Cloud", link: "/salesforce-marketing-cloud" },
                { title: "Salesforce Comunity Cloud", link: "/salesforce-community-cloud" },
                { title: "Salesforce Integration Cloud", link: "/salesforce-integration-cloud" },
                { title: "Salesforce Data Cloud", link: "/salesforce-data-cloud" },
              ],
            },
            {
              title: "ServiceNow",
              link: "#",
              submenus: [
                { title: "ServiceNow It Service Management", link: "/servicenow-it-service-management" },
                { title: "ServiceNow IT Workflows", link: "/servicenow-it-workflows" },
                { title: "ServiceNow Knowledge Management", link: "/servicenow-knowledge-management" },
                { title: "ServiceNow Audit Management", link: "/servicenow-audit-management" },
                { title: "ServiceNow Configuration Compliance", link: "/servicenow-configuration-compliance" },
                { title: "ServiceNow IT Operations Management", link: "/servicenow-it-operations-management" },
              ],
            },
            {
              title: "AWS",
              link: "#",
              submenus: [
                { title: "Aws Consulting", link: "/aws-consulting" },
                { title: "Aws Cloud Migration", link: "/aws-cloud-migration" },
                { title: "Aws Cloud Security", link: "/aws-cloud-security" },
                { title: "Managed Cloud Services", link: "/managed-cloud-services" },
                { title: "Serverless Computing", link: "/serverless-computing" },
                { title: "Aws Market Enablement", link: "/aws-market-enablement" },
              ],
            },
            {
              title: "SAP",
              link: "#",
              submenus: [
                { title: "Sap Hana", link: "/sap-hana" },
                { title: "Sap Crm", link: "/sap-crm" },
                { title: "Sap Erp", link: "/sap-erp" },
                { title: "Sap Hr", link: "/sap-hr" },
                { title: "Sap Business Objects", link: "/sap-business-objects" },
                { title: "Sap Plm", link: "/sap-plm" },
              ],
            },
            {
              title: "Analytics",
              link: "#",
              submenus: [
                { title: "Qlikview", link: "/qlikview" },
                { title: "Tableau", link: "/tableau" },
                { title: "Power-Bi", link: "/power-bi" },
                { title: "QlikSense", link: "/qliksense" },
                { title: "Sap-Analytics", link: "/sap-analytics" },
              ],
            },
            {
              title: "Microsoft Dynamics 365",
              link: "#",
              submenus: [
                { title: "Business Central", link: "/business-central" },
                { title: "Finance", link: "/finance" },
                { title: "Supply Chain Management", link: "/supply-chain-management" },
                { title: "Sales", link: "/sales" },
                { title: "Customer Service", link: "/customer-service" },
                { title: "Project Operations", link: "/field-service" },
                { title: "Marketing", link: "/marketing" },
                { title: "Human Resource", link: "/human-resource" },

              ],
            },
            {
              title: "Oracle",
              link: "#",
              submenus: [
                { title: "Tabs", link: "/implementation-and-consulting" },
                { title: "OCI AI Services", link: "/oci-ai-services" },
                { title: "Application Development", link: "/application-development" },
                { title: "OCI Solutions", link: "/oci-solutions" },
                { title: "Oracle Managed services", link: "/oracle-managed-services" },
                { title: "Advisory Services", link: "/advisory-services" },
              ],
            },
          ],
        },
        {
          id: 2,
          title: "Offering",
          megaMenu: true,
          link: "/",
          mega_menus: [
            {
              title: "Solution",
              link: "#",
              submenus: [
                { title: "ERP", link: "/erp" },
              ],
            },
            {
              title: "Services",
              link: "#",
              submenus: [
                { title: "Software Development", link: "/software-development" },
              ],
            },
          ],
        },
        {
          id: 3,
          hasDropdown: true,
          title: "Innovation",
          link: "/",
          // submenus: [
          //   { title: "Classic Style", link: "/portfolio" },
          //   { title: "Grid 3 Columns", link: "/portfolio-2" },
          //   // { title: "Gallery Style", link: "/portfolio-gallery" },
          //   { title: "Masonry Full", link: "/portfolio-masonry" },
          //   { title: "Metro Style", link: "/portfolio-metro" },
          //   { title: "Slider Style", link: "/portfolio-slider" },
          //   { title: "Classic Details", link: "/portfolio-details" },
          //   { title: "List With Details", link: "/portfolio-details-list" },
          //   { title: "Slider with Details", link: "/portfolio-details-slider" },
          //   { title: "Video With Details", link: "/portfolio-details-video" },
          // ],
        },
        {
          id: 4,
          hasDropdown: true,
          title: "Staff Augmentation",
          link: "/",
          // submenus: [
          //   { title: "Blog Standard", link: "/blog" },
          //   { title: "Blog Grid", link: "/blog-grid" },
          //   { title: "Blog Grid Boxed", link: "/blog-grid-2" },
          //   { title: "Blog Grid Sidebar", link: "/blog-grid-sidebar" },
          //   { title: "Blog List Sidebar", link: "/blog-list-sidebar" },
          //   { title: "Blog Masonry", link: "/blog-masonry" },
          //   { title: "Blog Details", link: "/blog-details" },
          //   { title: "Blog Details 2", link: "/blog-details-2" },
          // ],
        },
        {
          id: 5,
          title: "Company",
          megaMenu: true,
          link: "/",
          pages: true,
          // mega_menus: [
          //   {
          //     title: "Page Layout 1",
          //     link: "#",
          //     submenus: [
          //       { title: "About Us", link: "/about" },
          //       { title: "About Me", link: "/about-me" },
          //       { title: "Service Creative", link: "/services" },
          //       { title: "Service Standard", link: "/services-2" },
          //       { title: "Service Basic", link: "/services-3" },
          //       { title: "Service Details", link: "/service-details" },
          //       { title: "Help Center", link: "/help" },
          //     ],
          //   },
          //   {
          //     title: "Page Layout 2",
          //     link: "#",
          //     submenus: [
          //       { title: "Team Classic", link: "/team" },
          //       { title: "Team Details", link: "/team-details" },
          //       { title: "Event Details", link: "/event-details" },
          //       { title: "Job List", link: "/job" },
          //       { title: "Job Details", link: "/job-details" },
          //       { title: "Pricing Table", link: "/pricing" },
          //       { title: "Coming soon", link: "/coming-soon" },
          //     ],
          //   },
          //   {
          //     title: "Page Layout 3",
          //     link: "#",
          //     submenus: [
          //       { title: "Shop", link: "/shop" },
          //       { title: "Shop Right Sidebar", link: "/shop-right-sidebar" },
          //       { title: "Shop Details", link: "/product-details" },
          //       { title: "FAQs", link: "/faq" },
          //       { title: "Search Result", link: "/search" },
          //       { title: "Privacy & Policy", link: "/policy" },
          //       { title: "Terms & Conditions", link: "/terms" },
          //     ],
          //   },
          //   {
          //     title: "Page Layout 4",
          //     link: "#",
          //     submenus: [
          //       { title: "Error 404", link: "/404" },
          //       { title: "Login", link: "/login" },
          //       { title: "Register", link: "/register" },
          //       { title: "Forgot Password", link: "/forgot" },
          //       { title: "My Cart", link: "/cart" },
          //       { title: "My Wishlist", link: "/wishlist" },
          //       { title: "Checkout", link: "/checkout" },
          //     ],
          //   },
          // ],
        },
        // {
        //   id: 6,
        //   hasDropdown: true,
        //   title: "Contact",
        //   link: "/contact",
        //   submenus: [
        //     { title: "Contact Agency", link: "/contact" },
        //     { title: "Contact: Classic", link: "/contact-2" },
        //   ],
        // },
      ],
    };
  },
};
